### ISSUE TITLE
Assets missing

### ISSUE THREAD

**Issue by chaosfire** [cojuer/Castlelike#1]
very nice project! please re-upload the assets.:)

**Comment by cojuer** [comment]
Hi!
I know I'm ~~a bit~~ a lot late, but I finally updated this project, adding assets/demo level/fixing some bugs and etc. Simplest way to run would be to use zip with binary from release:

https://github.com/cojuer/Castlelike/releases/tag/v0.1.0

Some unobvious things from feedback I got (as I'm not sure I'll be fixing those and updating project anytime soon):
- RMB can be used to equip/unequip items and move items between loot and inventory;
- to attack enemies it is enough to just move in their direction;
- there is no way to check in-game which equipment slot corresponds to which armor type.
